#!/usr/bin/env python3
import subprocess

target = input("Enter IP or hostname: ")

command = ["ping", "-c", "1", target]

result = subprocess.run(
    command,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

if result.returncode == 0:
    print("[+] Target is REACHABLE (Alive)")
else:
    print("[-] Target is UNREACHABLE (Dead / ICMP Blocked)")
